certification_index:
    path:     /
    defaults: { _controller: "AppFreelancerBundle:Certification:index" }
    methods:  GET

certification_show:
    path:     /{id}/show
    defaults: { _controller: "AppFreelancerBundle:Certification:show" }
    methods:  GET

certification_new:
    path:     /new
    defaults: { _controller: "AppFreelancerBundle:Certification:new" }
    methods:  [GET, POST]

certification_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppFreelancerBundle:Certification:edit" }
    methods:  [GET, POST]

certification_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppFreelancerBundle:Certification:delete" }
    methods:  DELETE
