<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGwkvfjt\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGwkvfjt/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGwkvfjt.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGwkvfjt\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGwkvfjt\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Gwkvfjt',
    'container.build_id' => 'a143e996',
    'container.build_time' => 1522189335,
));
