<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPpkgkcf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPpkgkcf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPpkgkcf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPpkgkcf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPpkgkcf\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ppkgkcf',
    'container.build_id' => 'd6ab219e',
    'container.build_time' => 1524123311,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPpkgkcf');
